[project]
name = "bindex-electrum"
version = "0.0.0"
description = "â‚¿index Electrum Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.13.2",
    "aiorpcx==0.25.0",
    "pyzmq==27.1.0",
    "ruff==0.14.5",
    "ty==0.0.1a26",
]
